Before try
Within TRY block, before g() call
1
2
about to raise exception in g()
*** exception 11, divison by 0 in g()
After try
