#
# Snail compiler tests
#
#
# Test exception handling in SL compiler.
#

include "inputs/stdtypes.slib"

procedure f( i : int ) : int
{
    return i + 1;
}

exception ZeroDivision;
exception MathError;

procedure g( i : int ) : int
{
    if( i != 0 ) then
        return f( i ) / i
    else
        . "about to raise exception in g()";
        raise ZeroDivision( 11, "divison by 0 in g()" )
    endif
}

. "Before try\n";

inline bytecode procedure iwrite( i : int )
{
    IPRINT
}

inline bytecode procedure swrite( s : string )
{
    SPRINT
}

inline bytecode procedure nl()
{
    NEWLINE
}

try {

    try {
        . "Within TRY block, before g() call";
        . g( 2 );
        . g( 1 );
        . g( 0 );
        . "Within TRY block, after g() call\n";
    }

    catch ZeroDivision {
        swrite( "Cought exception 11, and reraising...\n" );
	raise ZeroDivision( 11, "eleven" );
    }
    catch MathError {
        swrite( "Cought exception 12, and reraising...\n" );
	raise MathError( 12, "twelve" );
    }
    catch( var msg : string ) {
        swrite( "*** exception " );
        swrite( msg );
        nl();
    }
}
catch ZeroDivision {
    swrite( "Cought exception 11 for the second time\n" );
}
catch( var msg : string ) {
    swrite( "*** second catch: exception " );
    swrite( msg );
    nl();
}


. "After catch";
